application: bjoern-monroes
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|fa|eot|otf|svg|ttf|woff|less|scss))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|fa|eot|otf|svg|ttf|woff|less|scss))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
